--creating a procedure--
create or replace procedure test_procedure is
begin
SELECT HB.LIST_URL,H.URL_ADDRESS,H.NAME,H.COUNTRY,U.USER_ID,U.USER_NAME,U.DESCRIPTION,U.IP,U.CONNECTION_STATUS
FROM HUB_LIST HB,HUB H,CONNECTION C,USERS U
WHERE HB.URL_ADDRESS=H.URL_ADDRESS
AND  HB.URL_ADDRESS=C.URL_ADDRESS
AND  C.USER_ID=U.USER_ID;
end;
execute test_procedure;
